- README.md
- src/index.js
- test/blank.test.js
- test/present.test.js
See https://github.com/airbnb/enzyme/issues/12#issuecomment-169374132
/cc @ljharb @andreasklinger @ayrton
> Introduce aliases of empty/exist

- src/assertions/checked.js
- src/assertions/className.js
- src/assertions/contain.js
- src/assertions/descendants.js
- src/assertions/disabled.js
- src/assertions/empty.js
- src/assertions/exist.js
- src/assertions/generic.js
- src/assertions/html.js
- src/assertions/id.js
- src/assertions/match.js
- src/assertions/ref.js
- src/assertions/selected.js
- src/assertions/tagName.js
- src/assertions/text.js
- src/assertions/value.js
- src/debug.js
- src/index.js
Make the assertion messages and the markup compilation lazy. Also, in some cases, the components under test might not be able to return an output, since some of their subcomponents do not render properly (when doing shallow rendering).
The issue was originally reported by @andreasklinger 
cc @ayrton @andreasklinger
> Make the assertion messages lazy

- src/ShallowTestWrapper.js
Hi.
I like to use chai-shortcuts for enzyme, but it brakes the best feature about shallow rendering.
React shallow renders only one level of component, and all nested components are mocked by default.
It's very useful because I can don't care about children components in my tests.
But chai-enzyme creates `this.el` in constructor, underhood it call React.renderToString that renders all tree and my tests are broken because I don't pass all dependences in context. (component that I test don't need them, only children)
Do you mind to make create `this.el` in lazy way?
> Don't create el in constructor for shallow

- src/index.js
- test/attr.test.js
- test/blank.test.js
- test/checked.test.js
- test/className.test.js
- test/contain.test.js
- test/data.test.js
- test/descendants.test.js
- test/disabled.test.js
- test/exist.test.js
- test/html.test.js
- test/id.test.js
- test/present.test.js
- test/prop.test.js
- test/ref.test.js
- test/selected.test.js
- test/state.test.js
- test/style.test.js
- test/tagName.test.js
- test/text.test.js
- test/value.test.js
The following assertion passes:
```
it('Reproduction path', () => {
const wrapper = shallow(<div />);
expect(undefined).to.have.attr('key', 'somekey');
});
```
It also passes on ```to.have.prop```
> to.have.attr passes when actual is undefined

- README.md
- test/prop.test.js
Fixes #10, I might even argue that the second argument of the generic assertions should be removed.
Because that would have made it easier to understand from the beginning.
> Improved prop chaining example fixes #10

- src/index.js
People who don't use babel currently have to do:
```js 
var chai-enzyme = require('chai-enzyme').default
// vs.
var chai-enzyme = require('chai-enzyme')
```
As suggested @ljharb in #16:
> Consumers should never have to interact with babel's CommonJS interop
> Module export

- .editorconfig
- README.md
- src/ChaiWrapper.js
- src/TestWrapper.js
- src/assertions/descendants.js
- src/chains/exactly.js
- src/index.js
- test/exactly.test.js
Makes it easier to assert that wrapper has a exact amount of a certain descendant. fixes #7.
As a bonus I've moved all the chai helper methods for adding assertions from the ```index.js``` to a seperate file.
> Added exactly for asserting the amount of descendants

- README.md
- package.json
Loosen up the cheerio dependency, since enzyme 1.5.0 now requires cheerio `^0.20.0` . /cc @lelandrichardson  [Fixes #28] [Closes #25]
Initially I tried removing the dependency, but we're requiring it in our codebase. (😓)
> Loosen up cheerio dependency

- src/CheerioTestWrapper.js
- src/ReactTestWrapper.js
- test/exist.test.js
Not sure if you're accepting PRs on this repo (no pressure), but here is a possible fix for #37. The `ShallowTestWrapper` was already using this approach of lazily computing the `el` property, so it seemed like a reasonable approach to take in the other wrappers.
> .not.exist interaction fixes #37

- README.md
I got stuck w/ an error `AssertionError: expected { Object (root, unrendered, ...) } to have a property '$$typeof'` because I forgot the parens. Seems like this is not common for other chai plugins I've seen, so it might help someone.
> Add a note on chai.use

- src/ChaiWrapper.js
- src/index.js
This fixes a bug in IE, due to the fact that `function.name` is [not supported in IE](http://stackoverflow.com/questions/6903762/function-name-not-supported-in-ie).
This makes `chainableBehavior = undefined` and consequently breaks the code, as shown in the picture.
This PR is a collaboration with @keithamus.
> fix: add missing name argument

- src/ReactTestWrapper.js
- test/attr.test.js
This wraps the mount wrapper in a `hasAttribute` check and if the value is falsey, it returns
true anyway - this way JSX like `<div itemScope />` will return true to having the itemscope
attribute.
Fixes #47. Closes #66 (picks up from @tleunen's work and completes it per @ljharb's comments).
Ping for people involved in #47: @vesln @tleunen @ljharb 
Ping for people involved in #66: @vesln @tleunen @ljharb @ayrton
> fix: ensure attributes with no value, or "slightly truthy values" pass .attr

- README.md
Because it's a chain that only works with `descendants`, I've indented it one more level. Let me know if you'd rather have it at the same level.
> Add `exactly()` to the table of contents

- src/assertions/text.js
The `String.prototype.includes` method is [not available in all browsers](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility) which causes errors when using the following test construct: 
```
expect(wrapper).to.contain.text("foo bar")
```
Instead we could use the well-supported `String.prototype.indexOf` method which is used in the [`chai` library itself](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L325).
Our current workaround is to use the following construct
```
expect(wrapper.text()).to.contain("foo bar")
```
but it would be great to get this fixed here too.
> Allow tests to run in more browsers by avoiding use of String.prototype.includes

- src/ShallowTestWrapper.js
- test/match.test.js
Using the `match` assertion appears to be deferring to the `is` function, which takes any valid EnzymeSelector (see https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/is.md).
However, when passing a react component by class object (not string) the matcher fails. This is because the `is` matcher for the ShallowTestWrapper is rendering the full HTML so it could also handle pseudo-classes (e.g. ':checked').
Given that EnzymeSelectors don't officially support psuedo-classes AND there are completely separate matchers for those already, I think it makes sense to make `match` directly use the default `is` function to be more consistent.
This change didn't break any specs, and I've added some new ones that were failing before the change.
> Fix: use enzyme `is` for `match` assertion

- README.md
I got into the trap of thinking that `expect(wrapper).to.have.style('marginTop')` would work (because I did it this way in my component), but what actually works is using dashes, eg `margin-top`.
Therefore, I think others will benefit from this small documentation change!
> Document that style assertions should not be camelCased

- src/assertions/descendants.js
- test/exactly.test.js
This is a minor item, but I noticed that if I had a test use the chain `expect(wrapper).to.have.exactly(0).descendants("foo")` it was being treated as if it was `expect(wrapper).to.have.descendants("foo")`.
Obviously the workaround is to use `.to.not.have.descendants(...)` but I figured it was worth fixing.
> handle `.exactly(0)`

- .travis.yml
- package.json
Ideally, you would want to run a test harness for both versions if you plan on supporting 3.x for a while.
> Allow for newer versions of chai and cheerio.

- README.md
- src/assertions/contain.js
- src/reactNodeToString.js
- test/contain.test.js
The enzyme [`contains` assertion](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/contains.md) accepts a node or an array of nodes as an argument. The current use of `react-element-to-jsx-string` prevents this from working in chai-enzyme. This PR allows the passing of an array of nodes and updates the documentation.
> Support an array of nodes in `contain`

- src/assertions/contain.js
- src/assertions/containMatchingElement.js
before, reactNodeToString was called no matter what. With this
change, it will only be called when the assert fails.
> increase performance of contain and containMatchingElement

- src/ReactTestWrapper.js
- src/ShallowTestWrapper.js
- test/inspect.test.js
Always convert the name to string when in `ShallowTestWrapper#inspect` and `ReactTestWrapper#inspect` so it still works for components that have a `Symbol` as a `displayName`.
Since `name` is always gonna be defined I think it is fine to just call `.toString`, although some logic could be added to look for just `Symbol` instances.
https://github.com/producthunt/chai-enzyme/issues/214
> Cannot convert a Symbol value to a string

- src/ShallowTestWrapper.js
- test/contain.test.js
(the first level components)
Fixes #218.
> shallow render error messages now only show components under test
